/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './App.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Dark Theme Tokens (Modo Gimnasio Principal)
        'primary': '#9fffac',
        'primary-container': '#13ec6d',
        'on-primary': '#003914',
        'on-primary-container': '#00652a',
        'inverse-primary': '#006e2e',
        'primary-fixed': '#67ff8c',
        'primary-fixed-dim': '#00e468',
        'on-primary-fixed': '#002109',
        'on-primary-fixed-variant': '#005321',

        'secondary': '#b6ccbc',
        'secondary-container': '#384b3f',
        'on-secondary': '#223429',
        'on-secondary-container': '#a5baab',
        'secondary-fixed': '#d2e8d8',
        'secondary-fixed-dim': '#b6ccbc',
        'on-secondary-fixed': '#0d1f15',
        'on-secondary-fixed-variant': '#384b3f',

        'tertiary': '#a0ffa7',
        'tertiary-container': '#45ea6e',
        'on-tertiary': '#003911',
        'on-tertiary-container': '#006525',
        'tertiary-fixed': '#6aff86',
        'tertiary-fixed-dim': '#3ce368',
        'on-tertiary-fixed': '#002107',
        'on-tertiary-fixed-variant': '#00531d',

        'background': '#131316',
        'on-background': '#e4e1e6',
        'surface': '#131316',
        'on-surface': '#e4e1e6',
        'surface-dim': '#131316',
        'surface-bright': '#39393c',
        'surface-container-lowest': '#0e0e11',
        'surface-container-low': '#1b1b1e',
        'surface-container': '#1f1f22',
        'surface-container-high': '#2a2a2d',
        'surface-container-highest': '#353438',
        'surface-variant': '#353438',
        'on-surface-variant': '#bacbb8',
        'surface-tint': '#00e468',
        'inverse-surface': '#e4e1e6',
        'inverse-on-surface': '#303033',

        'outline': '#859583',
        'outline-variant': '#3b4b3c',

        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',

        // Light Theme Tokens (Modo Día Limpio)
        'light-primary': '#00236f',
        'light-primary-container': '#1e3a8a',
        'light-on-primary': '#ffffff',
        'light-on-primary-container': '#90a8ff',
        'light-secondary': '#9d4300',
        'light-secondary-container': '#fd761a',
        'light-on-secondary': '#ffffff',
        'light-on-secondary-container': '#5c2400',
        'light-background': '#faf8ff',
        'light-surface': '#faf8ff',
        'light-on-surface': '#131b2e',
        'light-on-surface-variant': '#444651',
        'light-outline': '#757682',
        'light-outline-variant': '#c5c5d3',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'margin': '1rem',
        'gutter': '1rem',
      },
      fontFamily: {
        'inter': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md-mobile': ['20px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'title-sm': ['16px', { lineHeight: '22px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'stat-numeric': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'numeric-input': ['16px', { lineHeight: '22px', letterSpacing: '0.02em', fontWeight: '600' }],
        'timer-pill': ['14px', { lineHeight: '18px', letterSpacing: '0.03em', fontWeight: '700' }],
        'body-base': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'body-bold': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '600' }],
        'caption': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
      }
    },
  },
  plugins: [],
};
